### ISSUE TITLE
tss2_encrypt: ecc not yet supported

### ISSUE THREAD

**Issue by fansari** [tpm2-software/tpm2-tools#3143] opened 2022-10-08 16:30 UTC
When I try to use my signing key for encryption it does not work.

```
[fansari@bat keys]$ tss2_encrypt -p /P_ECCP256SHA256/HS/SRK/mySigningKey -i data.txt -o data.enc
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:332:Fapi_Encrypt_Finish() ErrorCode (0x00060002) ECC Encryption not yet supported
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:126:Fapi_Encrypt() ErrorCode (0x00060002) Data_Encrypt
Fapi_Encrypt(0x60002) - fapi:If called functionality isn't implemented
```

My FAPI uses the ECC profile. How can I do encryption then?

Next test was to create a primary key with RSA and loaded it to the TPM.

But something like this also does not work:

```
tss2_encrypt -p 0x81000002 -i data.txt -o data.enc
[fansari@bat keys]$ tss2_encrypt -p 0x81000002 -i data.txt -o data.enc
ERROR:fapi:src/tss2-fapi/fapi_util.c:263:init_explicit_key_path() Hierarchy cannot be determined.
ERROR:fapi:src/tss2-fapi/fapi_util.c:556:get_explicit_key_path() init_explicit_key_path ErrorCode (0x0006001d)
ERROR:fapi:src/tss2-fapi/fapi_util.c:1614:ifapi_load_keys_async() Compute explicit path. ErrorCode (0x0006001d)
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:290:Fapi_Encrypt_Finish() Load keys. ErrorCode (0x0006001d)
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:126:Fapi_Encrypt() ErrorCode (0x0006001d) Data_Encrypt
Fapi_Encrypt(0x6001D) - fapi:The provided path is bad
```
Next try:

```
fansari@bat keys]$ tss2_createkey --path="/P_RSA2048SHA256/HS/SRK/myEncryptionKey" --type="noDa"
New password:
Re-enter new password:
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:515:rel_path_to_abs_path() ErrorCode (0x00060034) FAPI not provisioned for path: P_RSA2048SHA256/HS/SRK/.
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:582:ifapi_keystore_load_async() ErrorCode (0x00060034) Object P_RSA2048SHA256/HS/SRK/ not found.
ERROR:fapi:src/tss2-fapi/fapi_util.c:1822:ifapi_load_key_finish() ErrorCode (0x00060034) Could not open: P_RSA2048SHA256/HS/SRK/
ERROR:fapi:src/tss2-fapi/fapi_util.c:3385:ifapi_key_create() LoadKey finish ErrorCode (0x00060034)
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:283:Fapi_CreateKey_Finish() Key create ErrorCode (0x00060034)
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:116:Fapi_CreateKey() ErrorCode (0x00060034) Key_Create
Fapi_CreateKey(0x60034) - fapi:Provisioning was not executed.
```

Yes - the FAPI is provisioned for ECC. But how can I work with RSA then?  

As far as I understood the FAPI can only be provisioned with either ECC or RSA? Or can I somehow do both?

**Comment by idesai** [comment] 2022-10-12 00:16
@JuergenReppSIT ?

**Comment by JuergenReppSIT** [comment] 2022-10-12 08:46
You could run a second provisioning with a rsa config file (The persistent handle in the P_RSA2048SHA256 has to be adapted if there is already a persistent ecc primary). Example:
```
alias prsa='TSS2_FAPICONF=/usr/local/etc/tpm2-tss/fapi-config-rsa.json'
prsa tss2_provison
prsa tss2_createkey -p /SRK/mykey -t decrypt
echo secret |prsa tss2_encrypt -p /SRK/mykey -i- -o crypt
prsa tss2_decrypt -p /SRK/mykey -i crypt -o-
```

**Comment by fansari** [comment] 2022-10-16 13:19
This does not work for some reason. I am asked for my endorsement key and if I enter it I get this error message:

```
[fansari@bat keys]$ ./provision-fapi-rsa.sh
Authorize /P_ECCP256SHA256/HE "Endorsement Hierarchy":
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error
ERROR:fapi:src/tss2-fapi/fapi_util.c:761:ifapi_init_primary_finish() ErrorCode (0x000009a2) FAPI Provision
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:581:Fapi_Provision_Finish() Init primary finish ErrorCode (0x000009a2)
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x000009a2) Provision
Fapi_Provision(0x9A2) - tpm:session(1):authorization failure without DA implications
```

This is my fapi-config-rsa.json:

```
[fansari@bat keys]$ cat /usr/local/etc/tpm2-tss/fapi-config-rsa.json
{
     "profile_name": "P_RSA2048SHA256",
     "profile_dir": "/etc/tpm2-tss/fapi-profiles/",
     "user_dir": "~/.local/share/tpm2-tss/user/keystore",
     "system_dir": "/var/lib/tpm2-tss/system/keystore",
     "tcti": "device:/dev/tpmrm0",
     "system_pcrs" : [],
     "log_dir" : "/run/tpm2-tss/eventlog/"
}
```

In /etc/tpm2-tss/fapi-profiles/P_RSA2048SHA256.json I have modified these lines:

```
"srk_template": "system,restricted,decrypt,0x81000002",
"ek_template":  "system,restricted,decrypt,0x81010002",
```

**Comment by JuergenReppSIT** [comment] 2022-10-16 13:32
@fansari Could you please attach your script ./provision-fapi-rsa.sh

**Comment by fansari** [comment] 2022-10-16 13:54
I have added them and changed the extensions to ".txt". Uploads with .sh and .json did not work.

**Comment by JuergenReppSIT** [comment] 2022-10-16 14:12
@fansari Thank you for the scirpt. During the first provisioning you have assigned an auth value the Endorsement hierarchy. Both EKs (ECC and RSA) are keys under the endorsement hierarchy. /P_ECCP256SHA256/HE and /P_RSA2048SHA256 describe the same hierarchy. So for the creation of the RSA EK you need the auth value from the first provisioning with the ECC profile (--authValueEh) If you do not want do change the auth value you should not use --authValueEh in the second provisioning . Otherwise the new auth value will be needed also for the hierarchy /P_ECCP256SHA256/HE.

**Comment by fansari** [comment] 2022-10-16 15:56
If I modify my script and remove these --authValue parameters it behaves same.

```
Authorize /P_ECCP256SHA256/HE "Endorsement Hierarchy":
WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:1143:Fapi_Provision_Finish() Evict control failed ErrorCode (0x000009a2)
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x000009a2) Provision
Fapi_Provision(0x9A2) - tpm:session(1):authorization failure without DA implications
```

**Comment by JuergenReppSIT** [comment] 2022-10-16 19:38
@fansari I could reproduce your error and will create a fix for: https://github.com/tpm2-software/tpm2-tss/issues/2438
As a workaround you could execute the provisioning for the two profiles without auth values for the hierarchies. The auth values for the hierarchies could be changed afterwards.

**Comment by JuergenReppSIT** [comment] 2022-10-17 18:35
@fansari Did you also create /P_RSA2048SHA256/HS/SRK/myEncryptionKey with TSS2_FAPICONF='/usr/local/etc/tpm2-tss/fapi-config-rsa.json'?

**Comment by JuergenReppSIT** [comment] 2022-10-17 19:49
@fansari Did the encryption work after adding TSS2_FAPICONF='/usr/local/etc/tpm2-tss/fapi-config-rsa.json' to create-encryption-key.txt?

**Comment by fansari** [comment] 2022-10-18 16:06
Yes - this is working now.

I did another test: I deleted the encryption key and recreated it.

Now I am no longer abe to decrypt the file.

Is this intended?

**Comment by JuergenReppSIT** [comment] 2022-10-18 17:03
@fansari Yes that's intended. The private key is stored in the keystore. If you delete the key with tss2_delete the key is lost.
Only the primary keys can be recreated.

**Comment by fansari** [comment] 2022-10-18 17:07
I am just thinking about the following scenario: you encrypt a file. Now you completey wipe the TPM.

Will you ever be able to decrypt this file?

**Comment by JuergenReppSIT** [comment] 2022-10-18 18:14
@fansari It depends on the hierarchy you are using. The storage primary seed of the SRK will be changed after tpm2_clear. So the SRK can't be recreated afterwards. The endorsement primary Seed (EPS) will not be changed by tpm2_clear. 
So tpm_clear can be used to ensure that no previously generated keys in the storage hierarchy may be used in the future.
The EPS seed will be changed by tpm2_changeeps where you need platform hierarchy authorization. But you should not use this command because the EK could not be recreated appropriate to the EK certificate afterwards.
But after the recreation of the primary keys you still need the encrypted keys in the keystore to decypt your files.

**Comment by fansari** [comment] 2022-10-22 11:54
I have tested this but when I try to reprovision I get error messages:

```
[fansari@bat setup]$ tss2_provision
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error
Authorize /HE "Endorsement Hierarchy":
WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
```

**Comment by JuergenReppSIT** [comment] 2022-10-22 12:16
@fansari Did you provide the correct password for the endorsement hierarchy? If the first trial for the creation of the EK fails with error BAD_AUTH, FAPI asks for the password of the endorsement hierarchy. The second trial then should work. Example:
```
$ tss2_delete -p /
$ tss2_provision
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:401:Esys_CreatePrimary_Finish() Received TPM Error 
Authorize /HE "Endorsement Hierarchy": 
$ tss2_list
/P_ECCP256SHA256/HE/EK:/P_ECCP256SHA256/HE:/P_ECCP256SHA256/LOCKOUT:.....
```

**Comment by fansari** [comment] 2022-10-22 12:36
I have now cleared the TPM and started again.

I also tried my script which hands over the passwords.

```
tss2_provision --authValueEh=xxx --authValueSh=xxx --authValueLockout=xxx
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error
Authorize /HE "Endorsement Hierarchy":
WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
Authorize /HS "CreatePrimary":
ERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:286:Esys_EvictControl_Finish() Esys called in bad sequence.
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:1116:Fapi_Provision_Finish() Evict control failed ErrorCode (0x00070007)
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x00070007) Provision
Fapi_Provision(0x70007) - esapi:Function called in the wrong order
```
I am asked for the "Endorsement Hirarchy" - so I enter the corresponding password.

**Comment by JuergenReppSIT** [comment] 2022-10-22 12:50
@fansari  Perhaps that's still the problem we already dicussed: https://github.com/tpm2-software/tpm2-tss/issues/2438
Did you still use a password for the owner hierarchy?

**Comment by JuergenReppSIT** [comment] 2022-10-22 13:04
@fansari During experimenting with FAPI provisioning where trials with authentication are made it makes sense to increase the auth failed counter temporally:
`tpm2_dictionarylockout -Tdevice:/dev/tpmrm0 --setup-parameters --max-tries=9999 --clear-lockout`

**Comment by fansari** [comment] 2022-10-22 13:20
I have reprovisioned the TPM and now I try this command:

```
tpm2_dictionarylockout -Tdevice:/dev/tpmrm0 --setup-parameters --max-tries=9999 --clear-lockout

WARNING:esys:src/tss2-esys/api/Esys_DictionaryAttackLockReset.c:288:Esys_DictionaryAttackLockReset_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_DictionaryAttackLockReset.c:98:Esys_DictionaryAttackLockReset() Esys Finish ErrorCode (0x00000921)
ERROR: Esys_DictionaryAttackLockReset(0x921) - tpm:warn(2.0): authorizations for objects subject to DA protection are not allowed at this time because the TPM is in DA lockout mode
ERROR: Failed DictionaryLockout Reset
WARNING:esys:src/tss2-esys/api/Esys_DictionaryAttackParameters.c:310:Esys_DictionaryAttackParameters_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_DictionaryAttackParameters.c:108:Esys_DictionaryAttackParameters() Esys Finish ErrorCode (0x00000921)
ERROR: Esys_DictionaryAttackParameters(0x921) - tpm:warn(2.0): authorizations for objects subject to DA protection are not allowed at this time because the TPM is in DA lockout mode
ERROR: Failed DictionaryLockout Setup
ERROR: Unable to run tpm2_dictionarylockout
```

**Comment by fansari** [comment] 2022-10-22 13:37
I think the answer is that I have to run this tpm2_dictionarylockout command before I do the provisioning. This works.

Now tpm2_clear gives a different error message:

```
[fansari@bat provision]$ tpm2_clear
WARNING:esys:src/tss2-esys/api/Esys_Clear.c:291:Esys_Clear_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Clear.c:97:Esys_Clear() Esys Finish ErrorCode (0x0000098e)
ERROR: Esys_Clear(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented
ERROR: Unable to run tpm2_clear
```

**Comment by JuergenReppSIT** [comment] 2022-10-22 14:00
@fansari After you have set the lockout auth value by `tss2_provision --authValueLockout=xxx` you must provide the lockout password: `tpm2_clear xxx`.

**Comment by fansari** [comment] 2022-10-22 14:19
This seems to work - at least I get no error.

But what is the effect? I still see the key list with "tss2_list" and the entries in /var/lib/tpm2-tss are also still there.

When I try to reprovision I get this message:

```
[fansari@bat provision]$ ./provision-fapi-ecc.sh
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:240:Fapi_Provision_Async() ErrorCode (0x00060035) Profile P_ECCP256SHA256 was already provisioned.
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:151:Fapi_Provision() ErrorCode (0x00060035) Provision
Fapi_Provision(0x60035) - fapi:Already provisioned
```

**Comment by fansari** [comment] 2022-10-22 14:36
So far I could not get around this "wrong order" error. Yes - I use separate passwords for owner, endorsement and lockout.

**Comment by JuergenReppSIT** [comment] 2022-10-22 16:58
@fansari This problem should be fixed with https://github.com/tpm2-software/tpm2-tss/pull/2439. As a workaround before provisioning you could temporally clear the auth value of the owner hierarchy before provisioning.
```
tpm2_changeauth -c o -p your_pwd ""
tss2_provision --authValueSh=your_pwd .....
```

**Comment by fansari** [comment] 2022-10-22 18:27
This has worked. To summarize this: as long as I have a backup of the user keystore I can recreate my keys.

But this is only true as long as I sill have my primary keys which are generated when the TPM is privisioned.

If the TPM chip is cleared, is defective or I buy a new motherboard with integrated TPM chip: then I cannot use my keys anymore.

Is it possible to create my own primary key which I can backup and use it for provisioning? Could this be used with  a fapi template?

**Comment by williamcroberts** [comment] 2022-10-24 17:09
> This has worked. To summarize this: as long as I have a backup of my user keystore I can recreate my keys.
> 
> But this is only true as long as I still have my primary keys which are generated when the TPM is privisioned.

Yes, as things like tpm2_clear will change the owner hierarchy seed and thus invalidate all keys as you won't be able to re-create the primary key used as the SRK.

> 
> If the TPM chip is cleared or defective or I buy a new motherboard with integrated TPM chip: then I cannot use my keys anymore regardless whether they were created under SRK or EK (at least this is what I understood from your comments).
> 

The EK, for all intents and purposes, never changes. So any key under the Endorsement hierarchy continues to work.

> Is it possible to create my own primary key which I can backup and use it for provisioning? Could this be used with a fapi template?

If you need keys to survive the lifetime of the SRK, it would be best to import them and back them up elsewhere. In theory, if you have the right attributes so a key can be exported (fixedtpm clear and I think fixedparent clear as well), you can use tpm2-pytss to export a tpm generated key in the clear. But that defeats the point of the TPM. Generally you would just generate a key external to the TPM and import to the TPM rather than generate on the TPM and export for a later import.

**Comment by fansari** [comment] 2022-10-24 20:18
I am unsure how exactly this should be done. I found this:

https://github.com/tpm2-software/tpm2-tools/issues/1773

I did these steps:

```
openssl genrsa -out private.pem 2048
openssl rsa -in private.pem -outform pem -pubout -out public.pem
tpm2_createprimary -C o -g sha256 -G rsa -c primary.ctx
tpm2_import -C primary.ctx -G rsa -i private.pem -u key.pub -r key.priv 
tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx 
```
There were no errors up to this point.

Next I did:

```
tpm2_evictcontrol -C o -c key.ctx 0x81000003 -P xxx
```
This also worked.

Next I created /usr/local/etc/fapi-confg-rsa_2.json.

```
{
     "profile_name": "P_RSA2048SHA256_2",
     "profile_dir": "/etc/tpm2-tss/fapi-profiles/",
     "user_dir": "~/.local/share/tpm2-tss/user/keystore",
     "system_dir": "/var/lib/tpm2-tss/system/keystore",
     "tcti": "device:/dev/tpmrm0",
     "system_pcrs" : [],
     "log_dir" : "/run/tpm2-tss/eventlog/"
}
```
In /etc/tpm2-tss/fapi-profiles/P_RSA2048SHA256_2.json I changed the SRK to

```
    "srk_template": "system,restricted,decrypt,0x81000003",
    "srk_description": "Storage root key SRK",
    "srk_persistent": 1,
    "ek_template":  "",
    "ek_description": "",
```
Then I tried provisioning the fapi with this:

```
export TSS2_FAPICONF='/usr/local/etc/tpm2-tss/fapi-config-rsa_2.json'
tss2_provision --authValueSh=xxx --authValueEh=xxx --authValueLockout=xxx
```
But this gives an error:

```
Authorize /P_ECCP256SHA256/HE "Endorsement Hierarchy":
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:798:Fapi_Provision_Finish() ErrorCode (0x00060025) No EK certificate found.
ERROR:esys:src/tss2-esys/esys_iutil.c:394:iesys_handle_to_tpm_handle() Error: Esys invalid ESAPI handle (ff).
ERROR:esys:src/tss2-esys/esys_iutil.c:1105:esys_GetResourceObject() Unknown ESYS handle. ErrorCode (0x0007000b)
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:138:Esys_FlushContext_Async() flushHandle unknown. ErrorCode (0x0007000b)
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x0007000b)
ERROR:fapi:src/tss2-fapi/fapi_util.c:1138:ifapi_session_clean() Cleanup session failed.
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x00060025) Provision
Fapi_Provision(0x60025) - fapi:No certificate
```

**Comment by williamcroberts** [comment] 2022-10-24 21:00
@fansari I'm assuming this is an actual TPM and not the simulator right?

@JuergenReppSIT or @AndreasFuchsTPM any ideas on why its complaining on EK cert?

**Comment by JuergenReppSIT** [comment] 2022-10-24 21:08
with `"ek_template":  ""` in the profile no appropriate  certificate for the EK with the template "" will be found. In this case
`"ek_cert_less":"yes"` should be used in the profile.

**Comment by williamcroberts** [comment] 2022-10-24 21:23
> with `"ek_template": ""` in the profile no appropriate certificate for the EK with the template "" will be found. In this case `"ek_cert_less":"yes"` should be used in the fapi config file.

I was wondering if that was the issue. So an even better solution would be for @fansari to copy a working profile and just modify the SRK handle to 0x80000003 to pick up this other SRK? I guess an even better option would be to just use FAPI to import a key, @JuergenReppSIT does FAPI have a TPM2_Import functionality?

**Comment by JuergenReppSIT** [comment] 2022-10-24 21:34
> @JuergenReppSIT does FAPI have a TPM2_Import functionality?
No currently Fapi_Import can only be used to import policies or public keys.
@williamcroberts @AndreasFuchsTPM Perhaps it would make sense to add this feature for 4.0?

**Comment by JuergenReppSIT** [comment] 2022-10-24 22:07
@fansari @williamcroberts It's possible to use a profile with an existing persistent primary SRK. This key will internally marked is "delete prohibited". Fapi_Delete can be executed the primary will  be removed from keystore but the presistent key will not be evicted. This will only work if the name of the generated SRK is equal to the name of the persistent key. So the example will not work. There should be an error message "SRK persistent handle already defined"-

**Comment by JuergenReppSIT** [comment] 2022-10-25 13:48
I also have to add: Fapi_Import can also import private keys which are exported by fapi with the public key of the new parent.

**Comment by williamcroberts** [comment] 2022-10-25 14:00
> I also have to add: Fapi_Import can also import private keys which are exported by fapi with the public key of the new parent.

Ahh the man page, at least for tss2_import, is oddly worded in a way where I stopped reading at the or.
```
DESCRIPTION
       tss2_import(1) - This command imports a JSON encoded policy or policy template and stores it under the provided path or  it  imports  a
       JSON encoded key under the provided path.
```
This seems more clear, perhaps we should open a PR?
```
DESCRIPTION
       tss2_import(1) - This command imports a JSON encoded key, policy or policy template and stores it under the provided path.
```
How can we take a TPM2 blob pair and get it JSON encoded?

**Comment by JuergenReppSIT** [comment] 2022-10-25 14:32
With Fapi_Export json data as describe in FAPI Spec 3.6 Exported key encoding can be generated.

**Comment by JuergenReppSIT** [comment] 2022-10-25 15:11
Here also an example how to use Fapi_Export with TPM2_Duplicate:
```
tss2_createkey -p /SRK/parent -t "restricted, decrypt, noDA" -a ""
tss2_exportkey -p /SRK/parent --exportedData=parent_pub
tss2 import --path=/ext/parent --importData=parent_pub
tss2_import -p /policy/duplicate -i pol_duplicate.json 
tss2_createkey -p /SRK/mydupkey --type="noDa, exportable, decrypt" --policyPath=/policy/duplicate -a ""
tss2_exportkey -p /SRK/mydupkey  --pathToPublicKeyOfNewParent=/ext/parent  --exportedData=export_key
tss2_import -i export_key -p /SRK/mykey
```
The policy:
```
{
    "description":"Description pol_duplicate",
    "policy":[
        {
             "type": "POLICYDUPLICATIONSELECT",
			"newParentPath": "ext/parent",

		}
    ]
}
```

**Comment by JuergenReppSIT** [comment] 2022-10-25 15:49
> This seems more clear, perhaps we should open a PR?
@williamcroberts  yes that makes sense. An perhaps with the PR it would be good to add examples to the man page of tss2_exportkey and tss2_import.

**Comment by fansari** [comment] 2022-10-25 17:21
I have tried with "ek_cert_less":"yes".

When I now try to provision the fapi I get this error message:

```
Authorize /P_ECCP256SHA256/HE "Endorsement Hierarchy":
Authorize /P_ECCP256SHA256/LOCKOUT "Lockout Hierarchy":
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:999:Fapi_Provision_Finish() ErrorCode (0x0006000b) SRK persistent handle already defined
WARNING:fapi:src/tss2-fapi/ifapi_io.c:427:ifapi_io_remove_directories() Removing: /root/.local/share/tpm2-tss/user/keystore/P_RSA2048SHA256_2/HE/EK/object.json
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x0006000b) Provision
Fapi_Provision(0x6000B) - fapi:A parameter has a bad value`
```

Yes - my persistent handle 0x81000003 is already defined. That was the idea after all.

Next idea was to remove then this persistent handle and let tss2_provision create the handle.

This was working. Now I remove again this handle and run through all the steps show above again.

After this I had the key created by openssl again in place.

```
tpm2_evictcontrol -C o -c 0x81000003
tpm2_createprimary -C o -g sha256 -G rsa -c primary.ctx -P xxx
tpm2_import -C primary.ctx -G rsa -i private.pem -u key.pub -r key.priv 
tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx 
tpm2_evictcontrol -C o -c key.ctx 0x81000003 -P xxx
```

Now my tss2_list looks like this:

```
/P_ECCP256SHA256/HE/EK:/P_ECCP256SHA256/HE:/P_ECCP256SHA256/HS/SRK:/P_ECCP256SHA256/HS:/P_ECCP256SHA256/LOCKOUT:/P_ECCP256SHA256/HN:/P_RSA2048SHA256/HE/EK:/P_RSA2048SHA256/HE:/P_RSA2048SHA256/HS/SRK:/P_RSA2048SHA256/HS:/P_RSA2048SHA256/LOCKOUT:/P_RSA2048SHA256/HN:/P_RSA2048SHA256_2/HS/SRK:/P_RSA2048SHA256_2/HS:/P_RSA2048SHA256_2/LOCKOUT:/P_RSA2048SHA256_2/HE:/P_RSA2048SHA256_2/HN:/P_RSA2048SHA256/HS/SRK/myEncryptionKey:/P_ECCP256SHA256/HS/SRK/mySigningKey
```

Next I want to create an encryption key with this:

```
export TSS2_FAPICONF='/usr/local/etc/tpm2-tss/fapi-config-rsa_2.json'
KEYPATH='/P_RSA2048SHA256_2/HS/SRK/myEncryptionKey'
tss2_createkey -p ${KEYPATH} -t decrypt
```

But this gives errors:

```
New password:
Re-enter new password:
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error
ERROR:fapi:src/tss2-fapi/fapi_util.c:1390:ifapi_get_sessions_finish() ErrorCode (0x000002c4) Create FAPI session finish
ERROR:fapi:src/tss2-fapi/fapi_util.c:3359:ifapi_key_create() ErrorCode (0x000002c4)  FAPI create session
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:283:Fapi_CreateKey_Finish() Key create ErrorCode (0x000002c4)
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:116:Fapi_CreateKey() ErrorCode (0x000002c4) Key_Create
Fapi_CreateKey(0x2C4) - tpm:parameter(2):value is out of range or is not correct for the context
```

**Comment by JuergenReppSIT** [comment] 2022-10-26 12:10
@fansari  That's really an interesting approach to integrate external keys into the fapi keystore.
You did replace the persistent SRK with your key. fapi uses the SRK as tpmkey for sessions which seems not to be possible with your key. I was curious what would happen if the EK (with no policy) was used instead. But I got the TPM error "authValue or authPolicy is not available" when the replaced EK was used to create a key.
So I think it's not possible to use an externally created private key in FAPI until the implementation is extended.

**Comment by fansari** [comment] 2022-10-26 17:48
Thank you for this information. This means I can test again when this new version will be available.

**Closed** 2022-12-02 16:40 UTC

**Comment by fansari** [comment] 2023-04-07 11:51
I saw this version 4 is available now. Is it now possible to create such a private key?

**Comment by JuergenReppSIT** [comment] 2023-04-07 12:18
@fansari Sorry, no it's still not possible.
