### ISSUE TITLE
tpm2_pcrlist failed

### ISSUE THREAD

**Issue by fl-symbotic** [tpm2-software/tpm2-tools#1584] opened 2019-07-03 18:44 UTC

**Comment by fl-symbotic** [comment] 2019-07-03 18:47
root@bcm958802ht16:~# export TPM2TOOLS_TCTI_NAME=device
root@bcm958802ht16:~# export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0
root@bcm958802ht16:~#  sudo -u tss tpm2_pcrlist -T device:/dev/tpmrm0

** (process:3188): WARNING **: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.3 was not provided by any .service files
ERROR: tcti init allocation routine failed for library: "tabrmd" options: "(null)"
ERROR: Could not load tcti, got: "tabrmd"

root@bcm958802ht16:~# ls -la /dev/tpm*
crw------- 1 root root  10,   224 Jun 12 00:02 /dev/tpm0
crw------- 1 root root 253, 65536 Jun 12 00:02 /dev/tpmrm0

root@bcm958802ht16:~# export TPM2TOOLS_DEVICE_FILE=/dev/tpm0
root@bcm958802ht16:~#  sudo -u tss tpm2_pcrlist -T device:/dev/tpm0

** (process:3445): CRITICAL **: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'com.intel.tss2.Tabrmd': timed out (service_start_timeout=25000ms)
ERROR: tcti init allocation routine failed for library: "tabrmd" options: "(null)"
ERROR: Could not load tcti, got: "tabrmd"

**Comment by joholl** [comment] 2019-07-12 09:21
Thank you for engaging with the open source community.  When you create issues at an open source project, please make sure to check the following points:

#### Create the issue at the correct repository
This might be difficult since it is not always clear where the error is coming from.
#### Format your issue properly
In GitHub, [markdown](https://github.github.com/gfm/) is used to format text. for instance, `~strikethrough~` will lead to ~strikethrough~ while ` ```multi-line code``` ` will lead to a code block:

```
multi-line code
````

#### Give context
   - Show what you tried. Tell us what you expected and what happened instead.
   - Indicate which version you are using? Is it a release or the upstream master code? If so, which commit are you working on?
   - Tell us what system you are using (e.g. which linux distribution, version)
   - List the versions of the dependencies. For instance, which version of `tpm2-abrmd` you are using?
#### Communicate properly
Similar to Email conversations, on issue trackers, people like to be spoken to, especially when you expect them to help you solve problems. Be sure to show effort before submitting the issue.

<br/>

Note that you can [edit your issue](https://developer.github.com/v3/issues/#edit-an-issue) at any time using the button in the upper-right corner.

<br/>

As for your problem: I could not reproduce the error.

**Comment by williamcroberts** [comment] 2019-07-12 14:08
When you use sudo, the environment variables are not propagated. You need `sudo -E` or to chown the file so your user can access to it.

Closing this, support questions should go to the mailing list documented in README.md

**Closed by williamcroberts** 2019-07-12 14:08 UTC
