### ISSUE TITLE
tpm2_checkquote: only RSA signatures are supported

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2068] opened 2020-05-27 15:45 UTC
`tpm2_quote` will sign quotes with ECCDSA attestation keys, but `tpm2_checkquote` can not validate the signatures since it explicitly calls `tpm2_openssl_get_public_RSA_from_pem()`: https://github.com/tpm2-software/tpm2-tools/blob/master/tools/misc/tpm2_checkquote.c#L62

Generating an ephemeral ECC key takes a fraction of a second compared to several seconds for an RSA attestation key, so it would be more efficient to use ECC AK instead.

**Comment by williamcroberts** [comment] 2020-05-29 03:14
Duplicate of #2053

**Closed by williamcroberts** 2020-05-29 03:14 UTC
Labels: enhancement, in progress
