### ISSUE TITLE
tpm2_flushcontext: what to do about sessions

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#1349] opened 2019-03-07 16:16 UTC
I don't know why the tests don't fail, but a `tpm2_flushcontext -l` (for loaded sessions) does fail on my physical TPM. ... and it should.

The reason is that a session carries all this meta-data and thus the corresponding ESYS_TR cannot be reconstructed from a mere tpm handle. Also the TPM should only accept TPMI_DH_OBJECT handles for the TPM2_ReadPublic() and that's where I get my error.

This raises the question, how to proceed about this. One possibility (and possibly the cleanest) would be to use `Tss2_Sys_FlushContext` for loaded and active sessions that do not have any context info left.

In parallel I'd add a bug to tpm2-tss such that a good error is returned if a session handle is attempted to be used in Esys_TR_FromTPMPublic()

Does that sound reasonable to all ?

**Comment by AndreasFuchsSIT** [comment] 2019-03-07 16:24
Having thought about this, I guess this could be a valuable addition to ESAPI... Some kind of direct flush...

**Comment by joshuagl** [comment] 2019-03-07 16:25
Agreed, having to call a `Tss2_Sys_` function seems like it exposes a deficiency in the ESAPI.

**Comment by AndreasFuchsSIT** [comment] 2019-03-07 16:30
Yep... Do you know why this is not failing in the integration tests ?

Here's an ugly patch to be used in case of urgency only:
```
diff --git a/tools/tpm2_flushcontext.c b/tools/tpm2_flushcontext.c
index df15e00..f73dad6 100644
--- a/tools/tpm2_flushcontext.c
+++ b/tools/tpm2_flushcontext.c
@@ -34,6 +34,7 @@
 #include <stdlib.h>
 
 #include <tss2/tss2_esys.h>
+#include <tss2/tss2_sys.h>
 
 #include "log.h"
 #include "tpm2_capability.h"
@@ -67,21 +68,19 @@ static const char *get_property_name(TPM2_HANDLE handle) {
     return "invalid";
 }
 
+struct ESYS_CONTEXT {
+    int state;      /**< The current state of the ESAPI context. */
+    TSS2_SYS_CONTEXT *sys;       /**< The SYS context used internally to talk to
+                                      the TPM. */
+};
+
 static bool flush_contexts_tpm2(ESYS_CONTEXT *ectx, TPM2_HANDLE handles[],
                           UINT32 count) {
 
     UINT32 i;
 
     for (i = 0; i < count; ++i) {
-
-        ESYS_TR handle;
-        bool ok = tpm2_util_sys_handle_to_esys_handle(ectx, handles[i],
-                    &handle);
-        if (!ok) {
-            return false;
-        }
-
-        TPM2_RC rval = Esys_FlushContext(ectx, handle);
+        TPM2_RC rval = Tss2_Sys_FlushContext(ectx->sys, handles[i]);
         if (rval != TPM2_RC_SUCCESS) {
             LOG_ERR("Failed Flush Context for %s handle 0x%x",
                     get_property_name(handles[i]), handles[i]);
```

**Comment by williamcroberts** [comment] 2019-04-25 15:11
@AndreasFuchsSIT I haven't followed this much. From what I gather:
1. the flushcontext -l should fail and you're able to reproduce it
2. a potential change to esapi is proposed
3. we could take this hack patch and apply it to fix your issue for now

How do you want to proceed?

**Comment by williamcroberts** [comment] 2019-06-07 18:36
@AndreasFuchsSIT @flihp  Ill be proposing the following:

Problem Statement: Esys_TR_FromTPMPublic() cannot convert a TPM2_HANDLE returned from getcap for a session into a usable ESYS_TR.

Proposal:
Modify Esys_TR_FromTPMPublic() behavior so if the handle is a session, that it skips the ReadPublic TPM call and populates an ESYS_TR resource object. This ESYS_TR representing an object, obviously, and correctly would fail if passed to a command that expects something like an NV object or regular object. This is in-line with existing behavior like NV objects, where certain commands will fail depending on the resource the ESYS_TR references.

**Comment by williamcroberts** [comment] 2019-06-07 18:44
Looks like we can just tag it with the existing IESYSC_SESSION_RSRC

**Comment by williamcroberts** [comment] 2019-06-07 18:52
See PR: https://github.com/tpm2-software/tpm2-tss/pull/1442 for an RFC implementation

**Comment by williamcroberts** [comment] 2019-07-08 16:59
The patch has been merged, however, now we need to make sure that a release of ESAPI containing that change is ready for 4.0 release, so I am not going to close that until a release is cut.

Secondly, I'll upload tests

**Comment by williamcroberts** [comment] 2019-07-30 15:26
2.3.0 in rc process.... I think it's safe to close.

**Closed by williamcroberts** 2019-07-30 15:26 UTC
Labels: bug, in progress
