### ISSUE TITLE
travis-ci builds fail randomly

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#1774] opened 2019-10-08 22:11 UTC
Not entirely certain but travis-ci builds fail at random and the failures seem to be when running those integration tests that involve openssl command line tools.

**Comment by idesai** [comment] 2019-10-08 22:12
@tstruk @pdxjohnny @flihp @diabonas any thoughts?

**Comment by tstruk** [comment] 2019-10-08 22:46
What's failing for me is the test/integration/tests/abrmd_policysigned.sh test with this error:

ERROR:esys:src/tss2-esys/api/Esys_PolicySigned.c:117:Esys_PolicySigned() Esys Finish ErrorCode (0x000005db) 
ERROR: Esys_PolicySigned(0x5DB) - tpm:parameter(5):the signature is not valid
ERROR: Could not build policysigned TPM
ERROR: Unable to run tpm2_policysigned

**Comment by pdxjohnny** [comment] 2019-10-08 23:03
I saw the same thing Tadeusz saw

**Comment by joholl** [comment] 2019-10-09 07:14
We experienced a similar problem when we loaded openssl-generated ECC keys with leading zero bytes (#1759). I suspect loading unpadded keys/digests.

**Comment by joholl** [comment] 2019-10-09 09:28
I could reproduce the problem: if an openssl-generated RSA key with unpadded modulus is loaded via `tpm2_loadexternal`, the build fails.

This issue is a duplicate of #1763

**Comment by idesai** [comment] 2019-10-09 15:50
> What's failing for me is the test/integration/tests/abrmd_policysigned.sh test with this error:
> 
> ERROR:esys:src/tss2-esys/api/Esys_PolicySigned.c:117:Esys_PolicySigned() Esys Finish ErrorCode (0x000005db)
> ERROR: Esys_PolicySigned(0x5DB) - tpm:parameter(5):the signature is not valid
> ERROR: Could not build policysigned TPM
> ERROR: Unable to run tpm2_policysigned

Exactly. What precedes this step is the OpenSSL signing of the command parameters.

**Comment by idesai** [comment] 2019-10-09 17:47
Hmmm... moving from "Why doesn't this work -----> Why does this work". I have a [PR](https://travis-ci.org/tpm2-software/tpm2-tools/builds/595717802?utm_source=github_status&utm_medium=notification) that fixes this but cannot explain Travis-ci behavior especially since both are valid ways of passing input to the OpenSSL command line.

**Closed** 2019-10-09 19:10 UTC
