### ISSUE TITLE
TPM2_unseal "Invalid nonce size"

### ISSUE THREAD

**Issue by 2raziel3** [tpm2-software/tpm2-tools#1415] opened 2019-04-13 08:16 UTC
Hi,

I have managed to create an object and make it persistent in the Physical TPM, running the master repositories for TSS abrmd and tools.
However when i boot up I get the following error;

![IMG_20190412_150014](https://user-images.githubusercontent.com/36970807/56076628-7ab5f480-5dcb-11e9-88ac-640b19738798.jpg)

the script that is running is as follows;
#!/bin/sh
set -e
echo "Unlocking via TPM" >&2
export TPM2TOOLS_TCTI="device:/dev/tpm0"
/usr/local/bin/tpm2_unseal -c 0x81000000 -L sha1:0,2,3,7 && exit
if [ $? -eq 0 ]; then
	exit
fi
/lib/cryptsetup/askpass "Unlocking the disk fallback $CRYPTTAB_SOURCE ($CRYPTTAB_NAME)\nEnter passphrase: "

when I try to manually unseal using the command from the script it fails with the following warning;

// 0xF - TPM2_RC_NONCE
        "invalid nonce size or nonce value mismatch",

**Comment by lestums** [comment] 2019-04-13 14:04
Hello !

You are actually facing two distinct issues in here :

1. I think the error "TPM2_RC_NONCE" you received is something that has already been noticed but with an other tool (see #1381). Can anyone else confirm that guess ?

2. The second issue is your script itself which miss preliminary setup steps, explaining your `/dev/tpm0 : no such file or directory`. 

This script is executed using the initramfs/initrd environment that has been setup in the early boot sequence. At this moment during the boot, Linux kernel won't load any dynamic modules unless requested to do so (using `insmod` or `modprobe`). If you use a common distribution kernel, TPM modules are declared as dynamic (e.g `CONFIG_TCG_TIS=m` and `CONFIG_TCG_CRB=m`). Therefore, when the unseal command is executed, required modules for TPM are not loaded yet, hence explaining the missing `/dev/tpm0` device.

For that problem to be solved you should :

If you don't or can't recompile the kernel, adding the following prior running the unseal :
- Check that the TPM device exists in `/sys/class/tpm` (else error)
- `modprobe tpm_tis`
- `/dev/tpm0` should then appear. Else : `mknod` using major/minor from `/sys/class/tpm/tpm0/dev`

If you can recompile your kernel :
- Add `CONFIG_TCG_TIS` as static module (`=y` instead of `=m`)
- Recompile and have a coffee break (depend on your build system)

Unless this is an CS assignment or you like doing it your own way (to learn or master the complete LUKS+TPM chain), i suggest you take a look at those tools that already solve or give valuable hints on the LUKS+TPM2 problem :

- **Clevis** : Developped and used by RedHat for NBDE but you can use it for local purposes : https://github.com/latchset/clevis
Need some good knowledge of preboot env as RedHat use `dracut` which is not used in non Red-Hat'ish distros (like Debian or Ubuntu that uses `initramfs-tools` or ArchLinux with `mkinitcpio`)
- https://github.com/rqou/tpm2-luks
- https://github.com/electrickite/luks-tpm2
And many more !

Hope this will help you !

**Comment by 2raziel3** [comment] 2019-04-13 15:36
Hi  @lestums ,

I wish this was a CS asignment, however I need to get this functioning for a work project. I will look into your the steps you recomend for the second issue I am having. Some of the items you have linked I have come across in my research but I will take another look thorugh them :)

**Comment by 2raziel3** [comment] 2019-04-14 16:23
Hi @lestums ,

Sorry for the delay,
so manually checking /sys/class/tpm i get confirmation of the dir exists
i then run modprobe tpm_tis.
I then get the same output when i run the script from the shell and on reboot.

**Comment by 2raziel3** [comment] 2019-04-14 16:42
Hi @lestums ,

So i figured one part out my script was pointing to the wronf directory so it should read as;
the script that is running is as follows;
#!/bin/sh
set -e
echo "Unlocking via TPM" >&2
export TPM2TOOLS_TCTI="device:/dev/tpmrm0"
/usr/local/bin/tpm2_unseal -c 0x81000000 -L sha1:0,2,3,7 && exit
if [ $? -eq 0 ]; then
exit
fi
/lib/cryptsetup/askpass "Unlocking the disk fallback $CRYPTTAB_SOURCE ($CRYPTTAB_NAME)\nEnter passphrase: "

So when i now run this from the console I get the 0x8f error: invlaid nonce size or nonce value mismatch

**Comment by 2raziel3** [comment] 2019-04-14 16:52
Sorry for the spam, with that change on reboot it cycles on cryptsetup failed, bad password or options?
and then eventually boots to initramfs.

**Comment by lestums** [comment] 2019-04-15 13:37
Hi, glad to see you could solve the TPM missing issue.

I will look at this `TPM2_RC_NONCE` and try to reproduce it with simulator.

Things related to cryptsetup are distinct from `tpm2-tools` issues. If you don't mind we can continue this discussion by mail instead :)

**Comment by 2raziel3** [comment] 2019-04-15 13:53
Hi ,

Happy to keep this via mail,

I have also tried a build using;
Tools = 3.1.4-rc0
tss = 2.1.3_rc0
abrmd = 2.1.1_rc0

for that I am getting an error code 0x1c4 or 0x284 for tpm2_evictcontrol

Not expecting you to look into this aswell, I only bring it up because I
have found both of these issues in the february mail archive.
Potentially that might help you find someone to collab with, seen as you
were asking in the origional thread.

One Quick question though are the release candidate vesrions supposed to be
more stable than the none rc versions.
May be me being stupid but I could not tell.

**Comment by williamcroberts** [comment] 2019-04-24 16:19
I don't know if it's related to #1381 but I have a patch over there to ESYS which seems to be fixing/avoiding the problem in the other issue filed. I have to do more investigation if this is the proper patch or not.

**Comment by williamcroberts** [comment] 2019-04-24 18:53
We have confirmation from the maintainer that is indeed the correct patch, so please test with that patch installed and report back.

**Comment by AndreasFuchsSIT** [comment] 2019-04-24 20:38
patch is merged in tpm2-tss/master
You can give that a try as well...

**Comment by 2raziel3** [comment] 2019-04-24 20:49
Will give it a try soon tonight.

**Comment by 2raziel3** [comment] 2019-04-25 02:30
Hi,

So i have re-built using the master repositories for all three, and the nonce issue is no resolved, so thank you massively for that.
Running my script manually now reveals the secret, however when i run this on boot from initramfs it fails to requiring the passphrase to be manually entered. I am guessing that some requirments are not being met to allow this script to function. Any further help would be appreciated.

**Closed** 2019-04-25 14:00 UTC
