### ISSUE TITLE
make fails with error make: *** No rule to make target `tools/aux/tpm2_print.c', needed by `tools/aux/tpm2_print.o'.  Stop.

### ISSUE THREAD

**Issue by devesh25427** [tpm2-software/tpm2-tools#992] opened 2018-04-18 12:13 UTC
tpm2_print.c is inside tools/_aux/ folder instead of tools/aux/ Makefile is checking inside incorrect folder.

**Comment by devesh25427** [comment] 2018-04-19 05:49
yes.. Both tpm2_print.c and tpm2_rc_decode.c are inside _aux/ and expected inside aux according to makefile.am.

**Comment by williamcroberts** [comment] 2018-04-20 17:10
This bug report is perplexing as our whole CI depends on Make, and everyone else seems to be building and _aux doesn't exist here:
https://github.com/tpm2-software/tpm2-tools/tree/master/tools

try:
```sh
# Warning back up any changes you want and switch to master
# This assumes origin is the repo
git fetch origin
git checkout master
git reset --hard origin/master
git clean -fdx
./bootstrap
./configure
make
```

**Comment by williamcroberts** [comment] 2018-04-24 15:54
Not reproducible. Closing.

**Closed by williamcroberts** 2018-04-24 15:54 UTC
